linttest: use t.Helper() to skip irrelevant funcs (#633)
With this, we can finally see the corrent filename in
failed test output.

Instead of this:

	--- FAIL: TestVoidResultUsedInAssignment (0.01s)
	    linttest.go:144: unexpected number of reports: expected 1, got 0
	    linttest.go:173: pattern 0 matched nothing: void function result used
	    linttest.go:178: >>> issues reported:
	    linttest.go:182: <<<

We get this:

	--- FAIL: TestVoidResultUsedInAssignment (0.01s)
	    basic_test.go:489: unexpected number of reports: expected 1, got 0
	    basic_test.go:489: pattern 0 matched nothing: void function result used
	    basic_test.go:489: >>> issues reported:
	    basic_test.go:489: <<<

basic_test.go is an actual file with the test and line=489 is a
line that executed the test itself.

Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>